---
title: "HW4"
author: "Zachary Wright"
date: "4/12/2022"
output: html_document
---

```{r setup, include=FALSE}
# code chunk specifies whether the R code, warnings, and output 
# will be included in the output files.
if (!require("tidyverse")) {
   install.packages("tidyverse")
   library(tidyverse)
}
if (!require("knitr")) {
   install.packages("knitr")
   library(knitr)
}
if (!require("plotly")) {
   install.packages("plotly")
   library(plotly)
}
if (!require("gapminder")) {
   install.packages("gapminder")
   library(gapminder)
}
if (!require("RCurl")) {
    install.packages("RCurl")             # Install RCurl package
    library("RCurl")
}
if (!require("colourpicker")) {
    install.packages("colourpicker")              
    library("colourpicker")
}
if (!require("gganimate")) {
    install.packages("gganimate")              
    library("gganimate")
}
if (!require("gifski")) {
    install.packages("gifski")              
    library("gifski")
}
if (!require("magick")) {
    install.packages("magick")              
    library("magick")
}
if (!require("grDevices")) {
    install.packages("grDevices")              
    library("grDevices")
}
if (!require("leaflet")) {
    install.packages("leaflet")              
    library("leaflet")
}
if (!require("maps")) {
    install.packages("maps")              
    library("maps")
}
if (!require("htmltools")) {
    install.packages("htmltools")              
    library("htmltools")
}
if (!require("leaflegend")) {
    install.packages("leaflegend")              
    library("leaflegend")
}
if (!require("geojsonio")) {
    install.packages("geojsonio")              
    library("geojsonio")
}
if (!require("rgdal")) {
    install.packages("rgdal")              
    library("rgdal")
}
if (!require("stringi")) {
    install.packages("stringi")              
    library("stringi")
}
if (!require("RColorBrewer")) {
    install.packages("RColorBrewer")              
    library("RColorBrewer")
}
if (!require("tigris")) {
    install.packages("tigris")              
    library("tigris")
}
if (!require("leafpop")) {
    install.packages("leafpop")              
    library("leafpop")
}
if (!require("leafem")) {
    install.packages("leafem")              
    library("leafem")
}
if (!require("tmap")) {
    install.packages("tmap")              
    library("tmap")
}
if (!require("tmaptools")) {
    install.packages("tmaptools")              
    library("tmaptools")
}
if (!require("readxl")) {
    install.packages("readxl")              
    library("readxl")
}
# knitr::opts_knit$set(root.dir = "C:/Users/75CPENG/OneDrive - West Chester University of PA/Documents")
# knitr::opts_knit$set(root.dir = "C:\\STA490\\w05"
knitr::opts_chunk$set(echo = TRUE,       
                      warning = FALSE,   
                      result = TRUE,   
                      message = FALSE)
```


```{r}

prez = read.csv("https://raw.githubusercontent.com/zackwright27/sta553/main/countypresidential_election_2000-2020.csv")
head(prez)

fips = read.csv("https://raw.githubusercontent.com/zackwright27/sta553/main/fips2geocode.csv")
head(fips)

```
state_po, county_name, county_fips, party, candidatevotes
```{r}

#makes only Democrats and Republicans appear in the data

prez1 <- filter(prez, (party == "DEMOCRAT" | party =="REPUBLICAN") & year == "2020")


#includes specific variables in the data set
prez2 = prez1[c(1,3,4,5,7,8,9,10)]


#renames variables in prez2 from county_fips to fips
prez3 <- rename(prez2, fips = county_fips)
prez3

# attempt to only print one winner for each county
if ((prez3$candidatevotes/prez3$totalvotes) > 0.50){
  print (x = "Winner")
} else {print (" ")}




```


```{r}

#merges fips and prez3 data sets by the common variable name "fips"
prez4 <- merge(prez3, fips, by = "fips")
#prez4

#recreates the proper listed variables from bullet point 3
prez5 <- prez4[c(1,2,3,4,5,8,9)]
prez5
```

```{r}
## preparing data
picture <- read.csv("https://github.com/pengdsci/sta553/raw/main/data/geojson-counties-fips.json")[,c(7,8,9, 17)]
us <- prez5[prez5$fips == 1,]
# geo styling
geostyle <- list(scope = 'usa',
                 projection = list(type = 'albers usa'),
                 showland = TRUE,
                 landcolor = toRGB("gray95"),
                 subunitcolor = toRGB("gray85"),
                 countrycolor = toRGB("gray85"),
                 countrywidth = 0.5,
                 subunitwidth = 0.5
               )
## plotting map
prez6 <- plot_geo(us, lat = ~lat, lon = ~lon, offline = FALSE) %>%
       add_markers(text = ~ county_name, 
                   color = "red", 
                   symbol = I("circle"), 
                   size = I(8), 
                   hoverinfo = "text" )   %>%
        layout( title = '2020 Presidential Results', geo = geostyle)
prez6
```


library(plotly)
library(rjson)
library("RColorBrewer")  # brewer.pal.info for list of color scales
```{r}
library(plotly)
library(rjson)
library("RColorBrewer")  # brewer.pal.info for list of color scales

url <- 'https://github.com/pengdsci/sta553/raw/main/data/geojson-counties-fips.json'  # contains geocode to define county boundaries in the choropleth map
counties <- rjson::fromJSON(file=url)  
#load("/Users/chengpeng/WCU/Teaching/2022Spring/STA553/RMaps/unemp.rda")
df=unemp
g <- list(
      scope = 'usa',
      projection = list(type = 'albers usa'),
      showlakes = TRUE,
      lakecolor = toRGB('white')
    )
###
fig <- plot_ly()  %>% 
  add_trace( type = "choropleth",
          geojson = counties,
        locations = df$fips,
                z = df$rate,
       colorscale = "GnBu",  
             zmin = 0,
             zmax = 30,
             text = df$name, # hover mesg
           marker = list(line=list(width=0.2))
          )   %>% 
  colorbar(title = "Unemployment Rate (%)")  %>% 
  layout( title = "US Unemployment by County",
          geo = g)
fig

```